on:
  workflow_call:

env:
  REPO: ${{ github.event.repository.name }}
  REPO_PATH: ~/${{ github.event.repository.name }}

jobs:
  bump-version:
    name: Bump Patch Version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          repository: TravelSizedLions/${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}

      - name: Checkout Additional Scripts
        uses: actions/checkout@v4
        with:
          repository: TravelSizedLions/actions
          path: actions

      - name: Copy Scripts
        run: |
          sudo cp -r actions/scripts $REPO/scripts
          find $REPO/scripts -name '*.sh' | xargs sudo chmod +x

      - name: Cache dasel
        id: cache-dasel
        uses: actions/cache@v4
        env:
          cache-name: dasel-install
        with:
          path: /usr/bin/dasel
          key: dasel-cache-key

      - name: Install dasel
        if: ${{ steps.cache-dasel.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get install -y dasel
          which dasel

      - name: Bump Patch Version
        id: bump
        run: cd $REPO && scripts/bump-patch.sh $REPO

      - name: Clean Up Scripts
        run: rm -rf $REPO/scripts

      - name: Tag & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "v${{ steps.bump.outputs.next_version }}"
          tagging_message: "v${{ steps.bump.outputs.next_version }}"
